version: '3.8'

services:
  # MySQL数据库 - 优先启动
  mysql:
    image: mysql:8.0
    container_name: wx-ai-chat-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: user123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  # 后端服务 - 依赖MySQL
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wx-ai-chat-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./app/static:/app/app/static
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  # 前端服务 - 依赖后端
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: wx-ai-chat-frontend
    ports:
      - "81:80"
    env_file:
      - ./web/.env
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: